// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5CtQdN7ZNuisdnXWgsbNlBef4L-r_QKU',
    appId: '1:231631833346:web:baba1a1fda1450eafa5a1b',
    messagingSenderId: '231631833346',
    projectId: 'advanceproj-8da3a',
    authDomain: 'advanceproj-8da3a.firebaseapp.com',
    storageBucket: 'advanceproj-8da3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-wG-SYXTuO07P98NuHtNLJzWRrIDGvY',
    appId: '1:231631833346:android:46ee6b2b4bfd6b1dfa5a1b',
    messagingSenderId: '231631833346',
    projectId: 'advanceproj-8da3a',
    storageBucket: 'advanceproj-8da3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb29w-xItdMoOYNd-jVmIfoixtyq7kEq8',
    appId: '1:231631833346:ios:7143215a034d2d69fa5a1b',
    messagingSenderId: '231631833346',
    projectId: 'advanceproj-8da3a',
    storageBucket: 'advanceproj-8da3a.appspot.com',
    iosClientId: '231631833346-kq51n1o4mfjgj99io5v6ldp7b9rqo8s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb29w-xItdMoOYNd-jVmIfoixtyq7kEq8',
    appId: '1:231631833346:ios:7143215a034d2d69fa5a1b',
    messagingSenderId: '231631833346',
    projectId: 'advanceproj-8da3a',
    storageBucket: 'advanceproj-8da3a.appspot.com',
    iosClientId: '231631833346-kq51n1o4mfjgj99io5v6ldp7b9rqo8s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.advancedproj',
  );
}
